module_order:
    - fastqc:
        name: 'FastQC (raw)'
        anchor: 'pre_fastqc'
        target: 'FastQC'
        path_filters_exclude:
            - '*.trimmed_fastqc.zip'
    - trimmomatic:
        name: 'Trimmomatic'
        path_filters:
            - '*_trim.log'
    - fastqc:
        name: 'FastQC (trimmed)'
        anchor: 'post_fastqc'
        target: 'FastQC'
        path_filters:
            - '*.trimmed_fastqc.zip'
    - picard/markdups:
        name: 'Mark Duplicates'
        path_filters:
            - '*.markdup.txt'
    - samtools/stats:
        name: 'BAM Stats'
        path_filters:
            - '*.stats'

run_modules:
    - fastqc
    - trimmomatic
    - picard/markdups
    - samtools/stats

sp:
    samtools/stats:
        contents: This file was produced by samtools stats
        shared: true

plots_force_interactive: True

show_analysis_time: False
show_analysis_paths: False